// Mocks generated by Mockito 5.0.15 from annotations
// in tv/test/presentation/pages/top_rated_tv_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloc/bloc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv/tv.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeTopRatedTvSeriesState_0 extends _i1.Fake
    implements _i2.TopRatedTvSeriesState {}

/// A class which mocks [TopRatedTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvSeriesCubit extends _i1.Mock
    implements _i2.TopRatedTvSeriesCubit {
  MockTopRatedTvSeriesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TopRatedTvSeriesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeTopRatedTvSeriesState_0())
          as _i2.TopRatedTvSeriesState);
  @override
  _i3.Stream<_i2.TopRatedTvSeriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.TopRatedTvSeriesState>.empty())
          as _i3.Stream<_i2.TopRatedTvSeriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i3.Future<void> getTopRatedTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvSeries, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  void emit(_i2.TopRatedTvSeriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i4.Change<_i2.TopRatedTvSeriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
